# CSRF protection bas√©e sur la session (plus fiable en production)
framework:
    form:
        csrf_protection:
            enabled: true
            field_name: '_token'
            token_id: submit
